# Generated by Django 4.2.4 on 2023-08-24 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DrustveneMreze',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime_mreze', models.CharField(max_length=100)),
                ('link_mreze', models.URLField()),
                ('ikona_mreze', models.ImageField(blank=True, null=True, upload_to='ikone_mreza/')),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime_linka', models.CharField(max_length=100)),
                ('link_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='PostavkePlatforme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime_platforme', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='favicons/')),
                ('politika_privatnosti', models.URLField(blank=True, null=True)),
                ('uvijeti_koristenja', models.URLField(blank=True, null=True)),
                ('facebook_link', models.URLField(blank=True, null=True)),
                ('instagram_link', models.URLField(blank=True, null=True)),
                ('whatsapp_link', models.URLField(blank=True, null=True)),
                ('dashboard_pocetna_header', models.CharField(blank=True, max_length=200, null=True)),
                ('dashboard_pocetna_opis', models.TextField(blank=True, null=True)),
                ('preplate_heading', models.CharField(blank=True, max_length=100, null=True)),
                ('lista_kanala_heading', models.CharField(blank=True, max_length=100, null=True)),
                ('novcanik_heading', models.CharField(blank=True, max_length=100, null=True)),
                ('podrska_heading', models.CharField(blank=True, max_length=100, null=True)),
                ('postavke_profila_heading', models.CharField(blank=True, max_length=100, null=True)),
                ('pocetna_kartica_balans_card_header', models.CharField(blank=True, max_length=100, null=True)),
                ('pocetna_kartica_balans_opis', models.TextField(blank=True, null=True)),
                ('pocetna_kartica_aktivne_usluge_card_header', models.CharField(blank=True, max_length=100, null=True)),
                ('pocetna_kartica_aktivne_usluge_opis', models.TextField(blank=True, null=True)),
                ('pocetna_kartica_usluge_koje_isticu_card_header', models.CharField(blank=True, max_length=100, null=True)),
                ('pocetna_kartica_usluge_koje_isticu_opis', models.TextField(blank=True, null=True)),
                ('novcanik_informacije_heder', models.CharField(blank=True, max_length=100, null=True)),
                ('novcanik_napodplati_novcanik_header', models.CharField(blank=True, max_length=100, null=True)),
                ('novcanik_nadoplati_novcanik_opis', models.TextField(blank=True, null=True)),
                ('email_opis', models.TextField(blank=True, null=True)),
                ('email_website_link', models.TextField(blank=True, null=True)),
                ('email_support_mail', models.TextField(blank=True, null=True)),
                ('email_support_phone', models.TextField(blank=True, null=True)),
                ('drustvene_mreze', models.ManyToManyField(blank=True, to='frontend.drustvenemreze')),
                ('linkovi', models.ManyToManyField(blank=True, to='frontend.link')),
            ],
        ),
    ]
