# Generated by Django 4.2.4 on 2023-08-24 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postavkeplatforme',
            name='test_obavjest',
            field=models.TextField(blank=True, null=True),
        ),
    ]
