# Generated by Django 4.2.4 on 2023-08-24 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_postavkeplatforme_test_obavjest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postavkeplatforme',
            name='test_obavjest',
        ),
    ]
