# Generated by Django 4.2.4 on 2023-08-29 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_remove_postavkeplatforme_test_obavjest'),
    ]

    operations = [
        migrations.AddField(
            model_name='postavkeplatforme',
            name='white_logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
