# Generated by Django 4.2.4 on 2023-08-24 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('start_date', models.DateTimeField(help_text='Datum kada će se obavijest početi prikazivati.')),
                ('end_date', models.DateTimeField(help_text='Datum kada će obavijest prestati prikazivati.')),
                ('is_active', models.BooleanField(default=True, help_text='Označite ako želite da se obavijest prikazuje ili ne prikazuje manualno.')),
            ],
        ),
        migrations.CreateModel(
            name='KategorijaKanala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='KontaktPoruka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=255)),
                ('prezime', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('telefon', models.CharField(max_length=20)),
                ('naslov', models.CharField(max_length=255)),
                ('poruka', models.TextField()),
                ('datum_poslano', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Novcanik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('korisnik', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=100)),
                ('cijena', models.DecimalField(decimal_places=2, max_digits=10)),
                ('trajanje_u_danima', models.PositiveIntegerField()),
                ('funkcije', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum_pocetka', models.DateTimeField(blank=True, null=True)),
                ('datum_isteka', models.DateTimeField()),
                ('datum_placanja', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('P', 'Plaćena'), ('N', 'Treba platiti'), ('E', 'Istekla')], default='N', max_length=1)),
                ('korisnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pretplata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='korisnici.subscription')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=100)),
                ('prezime', models.CharField(max_length=100)),
                ('drzava', models.CharField(max_length=100)),
                ('broj_mobitela', models.CharField(max_length=20)),
                ('m3u_username', models.CharField(blank=True, max_length=100, null=True)),
                ('m3u_password', models.CharField(blank=True, max_length=100, null=True)),
                ('m3u_link', models.TextField(blank=True, null=True)),
                ('is_m3u_active', models.BooleanField(default=False)),
                ('korisnik', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('novcanik', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='korisnici.novcanik')),
            ],
        ),
        migrations.CreateModel(
            name='Kanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=100)),
                ('kategorija', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='korisnici.kategorijakanala')),
            ],
        ),
    ]
