# Generated by Django 4.2.4 on 2023-08-24 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korisnici', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='mag_mac_adresa',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mag_model_uredjaja',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mag_sn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tip_usluge',
            field=models.CharField(blank=True, choices=[('M3U', 'M3U'), ('MAG', 'MAG')], max_length=4, null=True),
        ),
    ]
