# Generated by Django 4.2.4 on 2023-08-24 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('korisnici', '0003_alter_userprofile_mag_mac_adresa_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='mag_mac_adresa',
            new_name='mag_mac',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='mag_model_uredjaja',
            new_name='mag_model',
        ),
    ]
