# Generated by Django 4.2.4 on 2023-09-05 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korisnici', '0007_usersubscription_is_mag_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
