# Generated by Django 4.2.4 on 2023-09-05 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('korisnici', '0008_usersubscription_notification_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubscription',
            name='notification_sent',
        ),
    ]
