# Generated by Django 4.2.4 on 2023-09-05 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korisnici', '0009_remove_usersubscription_notification_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='korisnik_obavjesten_o_isteku',
            field=models.BooleanField(default=False),
        ),
    ]
