# Generated by Django 4.2.4 on 2023-09-05 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korisnici', '0010_usersubscription_korisnik_obavjesten_o_isteku'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='admin_obavjesten_o_isteku',
            field=models.BooleanField(default=False),
        ),
    ]
