# Generated by Django 4.2.4 on 2023-09-05 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korisnici', '0011_usersubscription_admin_obavjesten_o_isteku'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='korisnik_obavjesten_o_prekidu_usluge',
            field=models.BooleanField(default=False),
        ),
    ]
